spring:
  application:
    name: keep-in-touch
  datasource:
    url: jdbc:postgresql://localhost:5432/keepintouch
    username: postgres
    password: 1234567899
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    repair: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false